workflows:
  ios-workflow:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Football Alarm API"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_signing
      vars:
        APP_STORE_APPLE_ID: 6742335191
        BUNDLE_ID: "com.programgrubu.football.alarm1"
        APPLE_TEAM_ID: "3B9P62N8T2"
    scripts:
      - name: Clean and Fix gitignore
        script: |
          rm -f .gitignore
          printf "node_modules/\n.dart_tool/\n.packages\nbuild/\n" > .gitignore

      - name: Initialize Keychain
        script: keychain initialize
        
      - name: Set up Provisioning Profiles
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$CM_PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/football_alarm.mobileprovision
          
      - name: Set up Code Signing Certificate
        script: |
          echo "$CM_CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "$CM_CERTIFICATE_PASSWORD"
        
      - name: Flutter pub get
        script: flutter pub get
        
      - name: Configure Flutter iOS
        script: |
          # Bu komut imza aramadan dosyaları hazırlar.
          flutter build ios --config-only --release --no-codesign
        
      - name: Pod Install
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --repo-update
          
      - name: Flutter build ipa
        script: |
          # TestFlight için asıl imzalama burada gerçekleşir
          flutter build ipa --release \
            --export-method app-store \
            --build-number $(($BUILD_NUMBER + 100))
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true