workflows:
  ios-workflow:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Football Alarm API # Codemagic Integrations'taki anahtar adın
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_APPLE_ID: 6742335191 # Apple Store Connect'teki App ID (Gerekirse güncelle)
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Flutter build ipa
        script: |
          # Bu komut uygulamayı imzalar ve paketler
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true # Otomatik TestFlight'a gönderir
        beta_build_description: "Football Alarm iOS Versiyonu"