name: fb_alarm
description: "A new Flutter project for Football Alarms."
publish_to: 'none'
version: 1.0.1+13

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP istekleri
  http: ^1.2.0

  # Firebase servisleri
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Yerel Veri Saklama
  shared_preferences: ^2.2.3

  # Bildirim ve Alarm Sistemi
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^2.0.1

  # Arka Plan Görevleri
  workmanager: ^0.5.2

  # Reklam ve Ödeme
  google_mobile_ads: ^5.2.0
  in_app_purchase: ^3.2.0

  # Çevresel Değişkenler
  flutter_dotenv: ^6.0.0

  # İkonlar ve Tasarım
  cupertino_icons: ^1.0.6
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# Uygulama ikonu ayarları
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash/app_icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/splash/app_icon.jpg
    - .env