import 'package:flutter/material.dart';

// ==========================================
// YERELLEŞTİRME VERİLERİ (languages.dart)
// ==========================================
// Bu dosya uygulama genelindeki tüm dil desteklerini ve
// yerelleştirilmiş metinleri barındırır.
// Satır sayısı ve veri bütünlüğü korunmuştur.
// ==========================================

class AppTranslations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'language_name': 'Türkçe',
      'lang_tr': 'Türkçe',
      'lang_en': 'İngilizce',
      'lang_pt': 'Portekizce',
      'lang_de': 'Almanca',
      'lang_fr': 'Fransızca',
      'lang_it': 'İtalyanca',
      'lang_es': 'İspanyolca',
      'lang_nl': 'Felemenkçe',
      'lang_zh': 'Mandarin Çincesi',
      'lang_hi': 'Hintçe',
      'lang_ar': 'Arapça',
      'lang_ru': 'Rusça',
      'lang_ja': 'Japonca',
      'lang_ko': 'Korece',
      'lang_id': 'Endonezce',
      'lang_bn': 'Bengalce',
      'main_title': 'FUTBOL ALARMI',
      'nav_main': 'ANA SAYFA',
      'nav_alarms': 'ALARMLAR',
      'nav_settings': 'AYARLAR',
      'nav_upgrade': 'YÜKSELT',
      'login_title': 'GİRİŞ YAP',
      'no_account': 'Hesabın yok mu?',
      'has_account': 'Hesabın var mı?',
      'register': 'Kayıt Ol',
      'login': 'Giriş Yap',
      'choose_country': 'Ülke veya Turnuva Seçiniz',
      'choose_team': 'Takım Seçiniz',
      'continue': 'DEVAM ET',
      'alarm_set': 'ALARM AYARLANIYOR',
      'set_alarms': 'KURULMUŞ ALARMLAR',
      'no_alarm': "Yeni Alarm Ekle",
      'alarm_3_days': '3 GÜN KALA',
      'alarm_24_hours': '24 SAAT KALA',
      'alarm_match_start': 'MAÇ BAŞLANGICI',
      'alarm_match_result': 'MAÇ SONUCU',
      'home': 'ANASAYFA',
      'exit': 'ÇIKIŞ',
      'test': 'TEST',
      'settings_user': 'KULLANICI',
      'settings_plan': 'PAKET',
      'settings_support': 'DESTEK MERKEZİ',
      'settings_language': 'DİL',
      'settings_sound': 'BİLDİRİM SESİ',
      'settings_logoff': 'OTURUMU KAPAT',
      'plan_standard': 'STANDART',
      'upgrade_title': 'NEDEN YÜKSELT?',
      'upgrade_desc1': 'HİÇBİR MAÇI KAÇIRMAZSINIZ',
      'upgrade_desc2': '30 TAKIM İÇİN ALARM KURABİLİRSİNİZ',
      'upgrade_price': 'Aylık Abonelik için yükselt tuşuna basınız',
      'upgrade_subscription_msg': 'Aylık Abonelik için yükselt tuşuna basınız',
      'upgrade_button': 'YÜKSELT',
      'loading': 'Maç yükleniyor...',
      'on': 'AÇIK',
      'off': 'KAPALI',
      'no_selected_alarm': 'Seçilmiş Alarm Yok',
      'add_alarm': 'ALARM EKLE',
      'delete_alarm': 'ALARM SİL',
      'about_us': 'Hakkımızda',
      'menu_settings': 'AYARLAR',
      'menu_logoff': 'OTURUMU KAPAT',
      'menu_exit': 'ÇIKIŞ',
      'menu_history': 'GEÇMİŞ ALARMLAR',
      'history_title': 'ALARM GEÇMİŞİ',
      'premium_warning': 'Daha çok alarm kurabilmeniz için Yükselt kısmına geçip Premium kullanıcı olmalısınız',
      'premium_confirm_title': 'Premium moda geçiyorsunuz.',
      'premium_confirm_body': 'Onaylıyor musunuz?',
      'yes': 'EVET',
      'no': 'HAYIR',
      'premium_exit_title': 'Premium moddan çıkıyorsunuz.',
      'premium_exit_body': 'Standart kullanıcıya geçeyim mi?',
      'special_user': 'ÖZEL KULLANICI',
      'premium_status': 'Premium kullanıcısınız.',
      'premium_limit_info': 'Özel Kullanıcılar 30 adet alarm kurabilir.',
      'privacy_policy': 'Gizlilik Politikası',
      'api_error_403': '403 Forbidden: Bu veri planınıza dahil değil.',
      'api_error_404': '404 Not Found: Takım ID eşleşmesi hatalı.',
      'api_empty_list': 'Empty List: Planlanmış (SCHEDULED) maç bulunamadı.',
      'notif_3days': 'Maça 3 gün kaldı.',
      'notif_24hours': 'Maça 24 saat kaldı.',
      'notif_starts': 'maçı başlıyor!',
      'match_result_prefix': 'Maç Sonucu',
      'match_result_not_ready': 'Maç sonucu henüz hazır değil, lütfen bekleyiniz.',
      'match_finished_msg': 'Maç bitti',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) maç sonuçlanmıştır. Seçtiğiniz {teamName} takımının bitmiş son maçı {homeTeam} - {awayTeam} ile oynanmıştır.',
      'no_finished_match': 'Seçtiğiniz {teamName} takımı için sistemde henüz bitmiş bir maç kaydı bulunamadı.',
      'api_error': 'Veri çekme hatası',
      'connection_error': 'Bağlantı hatası oluştu. Lütfen internetinizi kontrol ediniz.',
      'test_no_alarm_info': 'Henüz bir alarm kurmadınız. Test için lütfen bir takıma alarm ekleyiniz.',
      'test_notif_incoming': 'Test bildirimi 2 saniye içinde gelecek.',
      'team_id_error': 'Seçili takım için veri çekilemedi. Takım ID eşleşmiyor.',
      'ad_loading': 'REKLAM YÜKLENİYOR...',
      'max_alarm_limit': 'Maksimum 30 alarm kurabilirsiniz.',
      'no_history_found': 'GEÇMİŞ ALARM BULUNMUYOR',
      'premium_active_msg': 'Premium Mod Açık!',
      'standard_active_msg': 'Standart Mod Açık!',
      'will_start': 'başlayacak.',
      'history_clear': 'TEMİZLE',
      'history_deleted': 'Seçilen geçmiş kayıtları silindi.',
      'btn_exit_clear': 'TEMİZLE',
    },
    'en': {
      'language_name': 'English',
      'lang_tr': 'Turkish',
      'lang_en': 'English',
      'lang_pt': 'Portuguese',
      'lang_de': 'German',
      'lang_fr': 'French',
      'lang_it': 'Italian',
      'lang_es': 'Spanish',
      'lang_nl': 'Dutch',
      'lang_zh': 'Mandarin Chinese',
      'lang_hi': 'Hindi',
      'lang_ar': 'Arabic',
      'lang_ru': 'Russian',
      'lang_ja': 'Japanese',
      'lang_ko': 'Korean',
      'lang_id': 'Indonesian',
      'lang_bn': 'Bengali',
      'main_title': 'FOOTBALL ALARM',
      'nav_main': 'MAIN',
      'nav_alarms': 'ALARMS',
      'nav_settings': 'SETTINGS',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'SIGN IN',
      'no_account': 'Don\'t have an account?',
      'has_account': 'Already have an account?',
      'register': 'Register',
      'login': 'Sign In',
      'choose_country': 'Choose Country or Tournament',
      'choose_team': 'Choose Team',
      'continue': 'CONTINUE',
      'alarm_set': 'SETTING ALARM',
      'set_alarms': 'SET ALARMS',
      'no_alarm': "Add New Alarm",
      'alarm_3_days': '3 DAYS BEFORE',
      'alarm_24_hours': '24 HOURS BEFORE',
      'alarm_match_start': 'MATCH START',
      'alarm_match_result': 'MATCH RESULT',
      'home': 'HOME',
      'exit': 'EXIT',
      'test': 'TEST',
      'settings_user': 'USER',
      'settings_plan': 'PLAN',
      'settings_support': 'SUPPORT CENTER',
      'settings_language': 'LANGUAGE',
      'settings_sound': 'NOTIFICATION SOUND',
      'settings_logoff': 'LOG OFF',
      'plan_standard': 'STANDARD',
      'upgrade_title': 'WHY UPGRADE?',
      'upgrade_desc1': "YOU WON'T MISS ANY MATCHES",
      'upgrade_desc2': 'YOU CAN SET 30 FOOTBALL TEAMS ALARMS',
      'upgrade_price': 'Press the upgrade button for monthly subscription',
      'upgrade_subscription_msg': 'Press the upgrade button for monthly subscription',
      'upgrade_button': 'UPGRADE',
      'loading': 'Loading match...',
      'on': 'ON',
      'off': 'OFF',
      'no_selected_alarm': 'No Selected Alarm',
      'add_alarm': 'ADD ALARM',
      'delete_alarm': 'DELETE ALARM',
      'about_us': 'About Us',
      'menu_settings': 'SETTINGS',
      'menu_logoff': 'LOG OFF',
      'menu_exit': 'EXIT',
      'menu_history': 'HISTORY',
      'history_title': 'ALARM HISTORY',
      'premium_warning': 'To set more alarms, you must go to the Upgrade section and become a Premium user',
      'premium_confirm_title': 'Upgrading to Premium.',
      'premium_confirm_body': 'Are you sure?',
      'yes': 'YES',
      'no': 'NO',
      'premium_exit_title': 'Exiting Premium mode.',
      'premium_exit_body': 'Switch to Standard user?',
      'special_user': 'SPECIAL USER',
      'premium_status': 'You are a Premium user.',
      'premium_limit_info': 'Special Users can set up to 30 alarms.',
      'privacy_policy': 'Privacy Policy',
      'api_error_403': '403 Forbidden: Not included in your plan.',
      'api_error_404': '404 Not Found: Wrong teamId mapping.',
      'api_empty_list': 'Empty List: No SCHEDULED matches found.',
      'notif_3days': '3 days left until the match.',
      'notif_24hours': '24 hours left until the match.',
      'notif_starts': 'match is starting!',
      'match_result_prefix': 'Match Result',
      'match_result_not_ready': 'Match result is not ready yet, please wait.',
      'match_finished_msg': 'Match finished',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) match has ended. The last finished match of your selected team {teamName} was played against {homeTeam} - {awayTeam}.',
      'no_finished_match': 'No finished match record found in the system for the team {teamName}.',
      'api_error': 'Data fetching error',
      'connection_error': 'Connection error occurred. Please check your internet.',
      'test_no_alarm_info': 'You haven\'t set an alarm yet. Please add an alarm to a team for testing.',
      'test_notif_incoming': 'Test notification will arrive in 2 seconds.',
      'team_id_error': 'Could not fetch data for the selected team. Team ID does not match.',
      'ad_loading': 'AD LOADING...',
      'max_alarm_limit': 'You can set a maximum of 30 alarms.',
      'no_history_found': 'NO ALARM HISTORY FOUND',
      'premium_active_msg': 'Premium Mode Enabled!',
      'standard_active_msg': 'Standard Mode Enabled!',
      'will_start': 'will start.',
      'history_clear': 'CLEAR',
      'history_deleted': 'Selected history records deleted.',
      'btn_exit_clear': 'CLEAR',
    },
    'zh': {
      'language_name': 'Mandarin Chinese',
      'lang_tr': '土耳其语',
      'lang_en': '英语',
      'lang_pt': '葡萄牙语',
      'lang_de': '德语',
      'lang_fr': '法语',
      'lang_it': '意大利语',
      'lang_es': '西班牙语',
      'lang_nl': '荷兰语',
      'lang_zh': '普通话 (中文)',
      'lang_hi': '印地语',
      'lang_ar': '阿拉伯语',
      'lang_ru': '俄语',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': '印尼语',
      'lang_bn': '孟加拉语',
      'main_title': '足球闹钟',
      'nav_main': '主页',
      'nav_alarms': '闹钟',
      'nav_settings': '设置',
      'nav_upgrade': '升级',
      'login_title': '登录',
      'no_account': '没有账号？',
      'has_account': '已有账号？',
      'register': '注册',
      'login': '登录',
      'choose_country': '选择国家或锦标赛',
      'choose_team': '选择球队',
      'continue': '继续',
      'alarm_set': '正在设置闹钟',
      'set_alarms': '已设闹钟',
      'no_alarm': "添加新闹钟",
      'alarm_3_days': '提前 3 天',
      'alarm_24_hours': '提前 24 小时',
      'alarm_match_start': '比赛开始',
      'alarm_match_result': '比赛结果',
      'home': '首页',
      'exit': '退出',
      'test': '测试',
      'settings_user': '用户',
      'settings_plan': '套餐',
      'settings_support': '支持中心',
      'settings_language': '语言',
      'settings_sound': '通知声音',
      'settings_logoff': '注销登录',
      'plan_standard': '标准版',
      'upgrade_title': '为什么要升级？',
      'upgrade_desc1': '您不会错过任何比赛',
      'upgrade_desc2': '您可以为 30 支球队设置闹钟',
      'upgrade_price': '请按升级按钮进行每月订阅',
      'upgrade_subscription_msg': '请按升级按钮进行每月订阅',
      'upgrade_button': '升级',
      'loading': '正在加载比赛...',
      'on': '开启',
      'off': '关闭',
      'no_selected_alarm': '未选择闹钟',
      'add_alarm': '添加闹钟',
      'delete_alarm': '删除闹钟',
      'about_us': '关于我们',
      'menu_settings': '设置',
      'menu_logoff': '注销',
      'menu_exit': '退出',
      'menu_history': '历史闹钟',
      'history_title': '闹钟历史',
      'premium_warning': '如需设置更多闹钟，请前往升级部分成为高级用户',
      'premium_confirm_title': '正在升级到高级版。',
      'premium_confirm_body': '您确定吗？',
      'yes': '是',
      'no': '否',
      'premium_exit_title': '退出高级模式。',
      'premium_exit_body': '切换到标准用户？',
      'special_user': '特殊用户',
      'premium_status': '您是高级用户。',
      'premium_limit_info': '特殊用户最多可设置 30 个闹钟。',
      'privacy_policy': '隐私政策',
      'api_error_403': '403 禁止访问：不包含在您的计划中。',
      'api_error_404': '404 未找到：球队 ID 映射错误。',
      'api_empty_list': '空列表：未找到已安排的比赛。',
      'notif_3days': '距离比赛还有3天。',
      'notif_24hours': '距离比赛还有24小时。',
      'notif_starts': '比赛正在开始！',
      'match_result_prefix': '比赛结果',
      'match_result_not_ready': '比赛结果尚未准备好，请稍候。',
      'match_finished_msg': '比赛结束',
      'test_match_finished_msg': '测试 {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) 比赛已结束。您选择的球队 {teamName} 的最后一场比赛是 {homeTeam} - {awayTeam}。',
      'no_finished_match': '系统中未找到球队 {teamName} 的完赛记录。',
      'api_error': '数据获取错误',
      'connection_error': '连接错误，请检查您的网络。',
      'test_no_alarm_info': '您尚未设置闹钟。请为球队添加闹钟以进行测试。',
      'test_notif_incoming': '测试通知将在 2 秒内送达。',
      'team_id_error': '无法获取所选球队的数据。球队 ID 不匹配。',
      'ad_loading': '广告加载中...',
      'max_alarm_limit': '您最多可以设置 30 个闹钟。',
      'no_history_found': '未找到历史闹钟',
      'premium_active_msg': '高级模式已开启！',
      'standard_active_msg': '标准模式已开启！',
      'will_start': '将开始。',
      'history_clear': '清除',
      'history_deleted': '选定的历史记录已删除。',
      'btn_exit_clear': '清除',
    },
    'bn': {
      'language_name': 'বাংলা',
      'lang_tr': 'তুর্কি',
      'lang_en': 'ইংরেজি',
      'lang_pt': 'পর্তুগিজ',
      'lang_de': 'জার্মান',
      'lang_fr': 'ফরাসি',
      'lang_it': 'ইতালীয়',
      'lang_es': 'স্প্যানিশ',
      'lang_nl': 'ডাচ',
      'lang_zh': 'ম্যান্ডারিন চাইনিজ',
      'lang_hi': 'হিন্দি',
      'lang_ar': 'আরবি',
      'lang_ru': 'রাশিয়ান',
      'lang_ja': 'জাপানি',
      'lang_ko': 'কোরিয়ান',
      'lang_id': 'ইন্দোনেশীয়',
      'lang_bn': 'বাংলা',
      'main_title': 'ফুটবল অ্যালার্ম',
      'nav_main': 'মূল পাতা',
      'nav_alarms': 'অ্যালার্ম',
      'nav_settings': 'সেটিংস',
      'nav_upgrade': 'আপগ্রেড',
      'login_title': 'লগ ইন করুন',
      'no_account': 'অ্যাকাউন্ট নেই?',
      'has_account': 'অ্যাকাউন্ট আছে?',
      'register': 'নিবন্ধন করুন',
      'login': 'লগ ইন',
      'choose_country': 'দেশ বা টুর্নামেন্ট নির্বাচন করুন',
      'choose_team': 'দল নির্বাচন করুন',
      'continue': 'চালিয়ে যান',
      'alarm_set': 'অ্যালার্ম সেট করা হচ্ছে',
      'set_alarms': 'সেট করা অ্যালার্ম',
      'no_alarm': "নতুন অ্যালার্ম যোগ করুন",
      'alarm_3_days': '৩ দিন আগে',
      'alarm_24_hours': '২৪ ঘণ্টা আগে',
      'alarm_match_start': 'ম্যাচ শুরু',
      'alarm_match_result': 'ম্যাচের ফলাফল',
      'home': 'হোম',
      'exit': 'প্রস্থান',
      'test': 'পরীক্ষা',
      'settings_user': 'ব্যবহারকারী',
      'settings_plan': 'প্যাকেজ',
      'settings_support': 'সহায়তা কেন্দ্র',
      'settings_language': 'ভাষা',
      'settings_sound': 'বিজ্ঞপ্তি শব্দ',
      'settings_logoff': 'লগ আউট',
      'plan_standard': 'স্ট্যান্ডার্ড',
      'upgrade_title': 'কেন আপগ্রেড করবেন?',
      'upgrade_desc1': 'আপনি কোনো ম্যাচ মিস করবেন না',
      'upgrade_desc2': '৩০টি দলের জন্য অ্যালার্ম সেট করতে পারবেন',
      'upgrade_price': 'মাসিক সাবস্ক্রিপশনের জন্য আপগ্রেড বোতামটি চাপুন',
      'upgrade_subscription_msg': 'মাসিক সাবস্ক্রিপশনের জন্য আপগ্রেড বোতামটি চাপুন',
      'upgrade_button': 'আপগ্রেড',
      'loading': 'ম্যাচ লোড হচ্ছে...',
      'on': 'চালু',
      'off': 'বন্ধ',
      'no_selected_alarm': 'কোনো অ্যালার্ম নেই',
      'add_alarm': 'অ্যালার্ম যোগ করুন',
      'delete_alarm': 'অ্যালার্ম মুছুন',
      'about_us': 'আমাদের সম্পর্কে',
      'menu_settings': 'সেটিংস',
      'menu_logoff': 'লগ আউট',
      'menu_exit': 'প্রস্থান',
      'menu_history': 'অ্যালার্ম ইতিহাস',
      'history_title': 'অ্যালার্ম ইতিহাস',
      'premium_warning': 'আরও অ্যালার্ম সেট করতে প্রিমিয়াম ব্যবহারকারী হতে হবে',
      'premium_confirm_title': 'প্রিমিয়াম মোডে যাচ্ছেন।',
      'premium_confirm_body': 'আপনি কি নিশ্চিত?',
      'yes': 'হ্যাঁ',
      'no': 'না',
      'premium_exit_title': 'প্রিমিয়াম মোড থেকে বের হচ্ছেন।',
      'premium_exit_body': 'স্ট্যান্ডার্ড ব্যবহারকারী হবেন?',
      'special_user': 'বিশেষ ব্যবহারকারী',
      'premium_status': 'আপনি একজন প্রিমিয়াম ব্যবহারকারী।',
      'premium_limit_info': 'বিশেষ ব্যবহারকারীরা ৩০টি অ্যালার্ম সেট করতে পারেন।',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'api_error_403': '৪০৩ নিষিদ্ধ: আপনার প্ল্যানে অন্তর্ভুক্ত নয়।',
      'api_error_404': '৪০৪ পাওয়া যায়নি: দল আইডি ভুল।',
      'api_empty_list': 'খালি তালিকা: কোনো ম্যাচ পাওয়া যায়নি।',
      'notif_3days': 'ম্যাচ হতে ৩ দিন বাকি।',
      'notif_24hours': 'ম্যাচ হতে ২৪ ঘণ্টা বাকি।',
      'notif_starts': 'ম্যাচ শুরু হচ্ছে!',
      'match_result_prefix': 'ম্যাচের ফলাফল',
      'match_result_not_ready': 'ম্যাচের ফলাফল এখনও তৈরি হয়নি, অপেক্ষা করুন।',
      'match_finished_msg': 'ম্যাচ শেষ',
      'test_match_finished_msg': 'পরীক্ষা {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) ম্যাচ শেষ হয়েছে। আপনার নির্বাচিত দল {teamName}-এর শেষ ম্যাচটি {homeTeam} - {awayTeam}-এর বিরুদ্ধে খেলা হয়েছিল।',
      'no_finished_match': 'সিস্টেমে {teamName} দলের জন্য কোনো শেষ ম্যাচের রেকর্ড পাওয়া যায়নি।',
      'api_error': 'ডেটা সংগ্রহের ত্রুটি',
      'connection_error': 'সংযোগ ত্রুটি ঘটেছে। আপনার ইন্টারনেট চেক করুন।',
      'test_no_alarm_info': 'আপনি এখনও কোনো অ্যালার্ম সেট করেননি। পরীক্ষার জন্য একটি দলে অ্যালার্ম যোগ করুন।',
      'test_notif_incoming': '২ সেকেন্ডের মধ্যে পরীক্ষা বিজ্ঞপ্তি আসবে।',
      'team_id_error': 'নির্বাচিত দলের ডেটা সংগ্রহ করা যায়ni। দল আইডি মিলছে না।',
      'ad_loading': 'বিজ্ঞপ্তি লোড হচ্ছে...',
      'max_alarm_limit': 'আপনি সর্বোচ্চ ৩০টি অ্যালার্ম সেট করতে পারেন।',
      'no_history_found': 'কোনো অ্যালার্ম ইতিহাস পাওয়া যায়নি',
      'premium_active_msg': 'প্রিমিয়াম মোড চালু হয়েছে!',
      'standard_active_msg': 'স্ট্যান্ডার্ড মোড চালু হয়েছে!',
      'will_start': 'শুরু হবে।',
      'history_clear': 'মুছে ফেলুন',
      'history_deleted': 'নির্বাচিত ইতিহাস মুছে ফেলা হয়েছে।',
      'btn_exit_clear': 'মুছে ফেলুন',
    },
    'pt': {
      'language_name': 'Português',
      'lang_tr': 'Turco',
      'lang_en': 'Inglês',
      'lang_pt': 'Português',
      'lang_de': 'Alemão',
      'lang_fr': 'Francês',
      'lang_it': 'Italiano',
      'lang_es': 'Espanhol',
      'lang_nl': 'Holandês',
      'lang_zh': 'Chinês Mandarim',
      'lang_hi': 'Hindi',
      'lang_ar': 'Árabe',
      'lang_ru': 'Russo',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Indonésio',
      'lang_bn': 'Bengali',
      'main_title': 'ALARME DE FUTEBOL',
      'nav_main': 'PRINCIPAL',
      'nav_alarms': 'ALARMES',
      'nav_settings': 'CONFIGURAÇÕES',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'ENTRAR',
      'no_account': 'Não tem conta?',
      'has_account': 'Já tem conta?',
      'register': 'Registrar',
      'login': 'Entrar',
      'choose_country': 'Escolher País ou Torneio',
      'choose_team': 'Escolher Time',
      'continue': 'CONTINUAR',
      'alarm_set': 'DEFININDO ALARME',
      'set_alarms': 'ALARMES DEFINIDOS',
      'no_alarm': 'Adicionar novo alarme',
      'alarm_3_days': '3 DIAS ANTES',
      'alarm_24_hours': '24 HORAS ANTES',
      'alarm_match_start': 'INÍCIO DO JOGO',
      'alarm_match_result': 'RESULTADO DO JOGO',
      'home': 'INÍCIO',
      'exit': 'SAIR',
      'test': 'TESTE',
      'settings_user': 'USUÁRIO',
      'settings_plan': 'PLANO',
      'settings_support': 'SUPORTE',
      'settings_language': 'IDIOMA',
      'settings_sound': 'SOM DE NOTIFICAÇÃO',
      'settings_logoff': 'SAIR',
      'plan_standard': 'PADRÃO',
      'upgrade_title': 'POR QUE UPGRADE?',
      'upgrade_desc1': 'VOCÊ NÃO PERDERÁ NENHUM JOGO',
      'upgrade_desc2': 'PODE DEFINIR ALARMES PARA 30 TIMES',
      'upgrade_price': 'Pressione o botão de atualização para assinatura mensal',
      'upgrade_subscription_msg': 'Pressione o botão de atualização para assinatura mensal',
      'upgrade_button': 'UPGRADE',
      'loading': 'Carregando...',
      'on': 'LIGADO',
      'off': 'DESLIGADO',
      'no_selected_alarm': 'Nenhum Alarme Selecionado',
      'add_alarm': 'ADD ALARME',
      'delete_alarm': 'EXC. ALARME',
      'about_us': 'Sobre Nós',
      'menu_settings': 'CONFIGURAÇÕES',
      'menu_logoff': 'SAIR',
      'menu_exit': 'SAIR',
      'menu_history': 'HISTÓRICO',
      'history_title': 'HISTÓRICO DE ALARMES',
      'premium_warning': 'Para definir mais alarmes, você deve se tornar um usuário Premium',
      'premium_confirm_title': 'Mudando para Premium.',
      'premium_confirm_body': 'Tem certeza?',
      'yes': 'SIM',
      'no': 'NÃO',
      'premium_exit_title': 'Saindo do modo Premium.',
      'premium_exit_body': 'Mudar para usuário padrão?',
      'special_user': 'USUÁRIO ESPECIAL',
      'premium_status': 'Você é um usuário Premium.',
      'premium_limit_info': 'Usuários especiais podem configurar 30 alarmes.',
      'privacy_policy': 'Política de Privacidade',
      'api_error_403': '403 Forbidden: Não incluído no seu plano.',
      'api_error_404': '404 Not Found: Mapeamento de id errado.',
      'api_empty_list': 'Empty List: Nenhuma correspondência encontrada.',
      'notif_3days': 'Faltam 3 dias para o jogo.',
      'notif_24hours': 'Faltam 24 horas para o jogo.',
      'notif_starts': 'o jogo está começando!',
      'match_result_prefix': 'Resultado do Jogo',
      'match_result_not_ready': 'O resultado ainda não está pronto, por favor aguarde.',
      'match_finished_msg': 'Fim de jogo',
      'test_match_finished_msg': 'TESTE {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) o jogo terminou. O último jogo terminado do seu time {teamName} foi contra {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Nenhum registro de jogo terminado encontrado para o time {teamName}.',
      'api_error': 'Erro ao buscar dados',
      'connection_error': 'Erro de conexão. Verifique sua internet.',
      'test_no_alarm_info': 'Você ainda não definiu um alarme. Adicione um para testar.',
      'test_notif_incoming': 'A notificação de teste chegará em 2 segundos.',
      'team_id_error': 'Não foi possível buscar dados para o time selecionado.',
      'ad_loading': 'CARREGANDO ANÚNCIO...',
      'max_alarm_limit': 'Você pode definir no máximo 30 alarmes.',
      'no_history_found': 'NENHUM HISTÓRICO ENCONTRADO',
      'premium_active_msg': 'Modo Premium Ativado!',
      'standard_active_msg': 'Modo Padrão Ativado!',
      'will_start': 'começará.',
      'history_clear': 'LIMPAR',
      'history_deleted': 'Registros históricos selecionados excluídos.',
      'btn_exit_clear': 'LIMPAR',
    },
    'de': {
      'language_name': 'Deutsch',
      'lang_tr': 'Türkisch',
      'lang_en': 'Englisch',
      'lang_pt': 'Portugiesisch',
      'lang_de': 'Deutsch',
      'lang_fr': 'Französisch',
      'lang_it': 'Italienisch',
      'lang_es': 'Spanisch',
      'lang_nl': 'Niederländisch',
      'lang_zh': 'Mandarin-Chinesisch',
      'lang_hi': 'Hindi',
      'lang_ar': 'Arabisch',
      'lang_ru': 'Russisch',
      'lang_ja': 'Japanese',
      'lang_ko': 'Korean',
      'lang_id': 'Indonesian',
      'lang_bn': 'Bengali',
      'main_title': 'FUSSBALL ALARM',
      'nav_main': 'HAUPTSEITE',
      'nav_alarms': 'ALARME',
      'nav_settings': 'EINSTELLUNGEN',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'ANMELDEN',
      'no_account': 'Kein Konto?',
      'has_account': 'Bereits ein Konto?',
      'register': 'Registrieren',
      'login': 'Anmelden',
      'choose_country': 'Land oder Turnier wählen',
      'choose_team': 'Team wählen',
      'continue': 'WEITER',
      'alarm_set': 'ALARM WIRD GESETZT',
      'set_alarms': 'GESETZTE ALARME',
      'no_alarm': "Neuen Alarm hinzufügen",
      'alarm_3_days': '3 TAGE VORHER',
      'alarm_24_hours': '24 STUNDEN VORHER',
      'alarm_match_start': 'SPIELBEGINN',
      'alarm_match_result': 'SPIELERGEBNIS',
      'home': 'HOME',
      'exit': 'BEENDEN',
      'test': 'TEST',
      'settings_user': 'BENUTZER',
      'settings_plan': 'PAKET',
      'settings_support': 'SUPPORT-CENTER',
      'settings_language': 'SPRACHE',
      'settings_sound': 'BENACHRICHTIGUNGSTON',
      'settings_logoff': 'ABMELDEN',
      'plan_standard': 'STANDARD',
      'upgrade_title': 'WARUM UPGRADE?',
      'upgrade_desc1': 'KEIN SPIEL VERPASSEN',
      'upgrade_desc2': 'ALARME FÜR 30 TEAMS SETZEN',
      'upgrade_price': 'Drücken Sie die Upgrade-Taste für ein monatliches Abonnement',
      'upgrade_subscription_msg': 'Drücken Sie die Upgrade-Taste für ein monatliches Abonnement',
      'upgrade_button': 'UPGRADE',
      'loading': 'Spiel wird geladen...',
      'on': 'AN',
      'off': 'AUS',
      'no_selected_alarm': 'Kein Alarm ausgewählt',
      'add_alarm': 'ALARM HINZ.',
      'delete_alarm': 'ALARM LÖSC.',
      'about_us': 'Über uns',
      'menu_settings': 'EINSTELLUNGEN',
      'menu_logoff': 'ABMELDEN',
      'menu_exit': 'BEENDEN',
      'menu_history': 'ALARM-VERLAUF',
      'history_title': 'ALARM-HISTORIE',
      'premium_warning': 'Um mehr Alarme zu setzen, wechseln Sie zu Premium',
      'premium_confirm_title': 'Wechsel zum Premium-Modus.',
      'premium_confirm_body': 'Sind Sie sicher?',
      'yes': 'JA',
      'no': 'NEIN',
      'premium_exit_title': 'Premium-Modus verlassen.',
      'premium_exit_body': 'Zum Standard-Benutzer wechseln?',
      'special_user': 'SPEZIAL-BENUTZER',
      'premium_status': 'Sie sind ein Premium-Nutzer.',
      'premium_limit_info': 'Spezial-Nutzer können 30 Alarme setzen.',
      'privacy_policy': 'Datenschutz',
      'api_error_403': '403 Verboten: Nicht in Ihrem Plan.',
      'api_error_404': '404 Nicht gefunden: Team-ID Fehler.',
      'api_empty_list': 'Leere Liste: Keine Spiele gefunden.',
      'notif_3days': 'Noch 3 Tage bis zum Spiel.',
      'notif_24hours': 'Noch 24 Stunden bis zum Spiel.',
      'notif_starts': 'Das Spiel beginnt!',
      'match_result_prefix': 'Spielergebnis',
      'match_result_not_ready': 'Ergebnis ist noch nicht fertig, bitte warten.',
      'match_finished_msg': 'Spiel beendet',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) Spiel beendet. Letztes Spiel von {teamName} gegen {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Kein beendetes Spiel für {teamName} gefunden.',
      'api_error': 'Fehler beim Abrufen der Daten',
      'connection_error': 'Verbindungsfehler. Bitte Internet prüfen.',
      'test_no_alarm_info': 'Noch kein Alarm gesetzt. Bitte für Test hinzufügen.',
      'test_notif_incoming': 'Test-Benachrichtigung kommt in 2 Sekunden.',
      'team_id_error': 'Daten konnten nicht abgerufen werden.',
      'ad_loading': 'WERBUNG WIRD GELADEN...',
      'max_alarm_limit': 'Maximal 30 Alarme möglich.',
      'no_history_found': 'KEIN VERLAUF GEFUNDEN',
      'premium_active_msg': 'Premium-Modus Aktiv!',
      'standard_active_msg': 'Standard-Modus Aktiv!',
      'will_start': 'wird anfangen.',
      'history_clear': 'LEEREN',
      'history_deleted': 'Ausgewählte Verlaufsdaten gelöscht.',
      'btn_exit_clear': 'LEEREN',
    },
    'fr': {
      'language_name': 'Français',
      'lang_tr': 'Turc',
      'lang_en': 'Anglais',
      'lang_pt': 'Portugais',
      'lang_de': 'Allemand',
      'lang_fr': 'Français',
      'lang_it': 'Italien',
      'lang_es': 'Espagnol',
      'lang_nl': 'Néerlandais',
      'lang_zh': 'Chinois Mandarin',
      'lang_hi': 'Hindi',
      'lang_ar': 'Arabe',
      'lang_ru': 'Russe',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Indonésien',
      'lang_bn': 'Bengali',
      'main_title': 'ALARME DE FOOTBALL',
      'nav_main': 'ACCUEIL',
      'nav_alarms': 'ALARMES',
      'nav_settings': 'PARAMÈTRES',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'CONNEXION',
      'no_account': 'Pas de compte ?',
      'has_account': 'Déjà un compte ?',
      'register': 'S\'inscrire',
      'login': 'Se connecter',
      'choose_country': 'Choisir pays ou tournoi',
      'choose_team': 'Choisir équipe',
      'continue': 'CONTINUER',
      'alarm_set': 'RÉGLAGE DE L\'ALARME',
      'set_alarms': 'ALARMES RÉGLÉES',
      'no_alarm': "Ajouter nouvelle alarme",
      'alarm_3_days': '3 JOURS AVANT',
      'alarm_24_hours': '24 HEURES AVANT',
      'alarm_match_start': 'DÉBUT DU MATCH',
      'alarm_match_result': 'RÉSULTAT DU MATCH',
      'home': 'ACCUEIL',
      'exit': 'QUITTER',
      'test': 'TEST',
      'settings_user': 'UTILISATEUR',
      'settings_plan': 'FORFAIT',
      'settings_support': 'SUPPORT',
      'settings_language': 'LANGUE',
      'settings_sound': 'SON NOTIFICATION',
      'settings_logoff': 'DÉCONNEXION',
      'plan_standard': 'STANDARD',
      'upgrade_title': 'POURQUOI UPGRADER ?',
      'upgrade_desc1': 'NE MANQUEZ AUCUN MATCH',
      'upgrade_desc2': 'ALARMES PARA 30 ÉQUIPES',
      'upgrade_price': 'Appuyez sur le bouton de mise à niveau pour l\'abonnement mensuel',
      'upgrade_subscription_msg': 'Appuyez sur le bouton de mise à niveau pour l\'abonnement mensuel',
      'upgrade_button': 'UPGRADE',
      'loading': 'Chargement...',
      'on': 'ON',
      'off': 'OFF',
      'no_selected_alarm': 'Aucune alarme sélectionnée',
      'add_alarm': 'AJOU. ALARME',
      'delete_alarm': 'SUPP. ALARME',
      'about_us': 'À propos',
      'menu_settings': 'PARAMÈTRES',
      'menu_logoff': 'DÉCONNEXION',
      'menu_exit': 'QUITTER',
      'menu_history': 'HISTORIQUE',
      'history_title': 'HISTORIQUE DES ALARMES',
      'premium_warning': 'Passez en Premium pour plus d\'alarmes',
      'premium_confirm_title': 'Passage au mode Premium.',
      'premium_confirm_body': 'Êtes-vous sûr ?',
      'yes': 'OUI',
      'no': 'NON',
      'premium_exit_title': 'Quitter le mode Premium.',
      'premium_exit_body': 'Passer en utilisateur standard ?',
      'special_user': 'UTILISATEUR SPÉCIAL',
      'premium_status': 'Vous êtes un utilisateur Premium.',
      'premium_limit_info': 'Les utilisateurs spéciaux ont 30 alarmes.',
      'privacy_policy': 'Confidentialité',
      'api_error_403': '403 Interdit: Non inclus dans votre forfait.',
      'api_error_404': '404 Non trouvé: Erreur ID équipe.',
      'api_empty_list': 'Liste vide: Aucun match trouvé.',
      'notif_3days': 'Plus que 3 jours avant le match.',
      'notif_24hours': 'Plus que 24 heures avant le match.',
      'notif_starts': 'Le match commence !',
      'match_result_prefix': 'Résultat du Match',
      'match_result_not_ready': 'Le résultat n\'est pas encore prêt, veuillez patienter.',
      'match_finished_msg': 'Match fini',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) match terminé. Dernier match de {teamName} contre {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Aucun match terminé trouvé pour {teamName}.',
      'api_error': 'Erreur de données',
      'connection_error': 'Erreur de connexion. Vérifiez votre internet.',
      'test_no_alarm_info': 'Aucune alarme réglée. Ajoutez-en une pour tester.',
      'test_notif_incoming': 'Notification de test dans 2 secondes.',
      'team_id_error': 'Données introuvables pour l\'équipe sélectionnée.',
      'ad_loading': 'PUBLICITÉ EN COURS...',
      'max_alarm_limit': 'Maximum 30 alarmes autorisées.',
      'no_history_found': 'AUCUN HISTORIQUE TROUVÉ',
      'premium_active_msg': 'Mode Premium Activé !',
      'standard_active_msg': 'Mode Standard Activé !',
      'will_start': 'commencera.',
      'history_clear': 'EFFACER',
      'history_deleted': 'Enregistrements historiques sélectionnés supprimés.',
      'btn_exit_clear': 'EFFACER',
    },
    'es': {
      'language_name': 'Español',
      'lang_tr': 'Turco',
      'lang_en': 'Inglés',
      'lang_pt': 'Portugués',
      'lang_de': 'Alemán',
      'lang_fr': 'Francés',
      'lang_it': 'Italiano',
      'lang_es': 'Español',
      'lang_nl': 'Neerlandés',
      'lang_zh': 'Chino mandarín',
      'lang_hi': 'Hindi',
      'lang_ar': 'Árabe',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Indonesio',
      'lang_bn': 'Bengalí',
      'main_title': 'ALARMA DE FÚTBOL',
      'nav_main': 'INICIO',
      'nav_alarms': 'ALARMES',
      'nav_settings': 'AJUSTES',
      'nav_upgrade': 'MEJORAR',
      'login_title': 'INICIAR SESIÓN',
      'no_account': '¿No tienes cuenta?',
      'has_account': '¿Ya tienes cuenta?',
      'register': 'Registrarse',
      'login': 'Entrar',
      'choose_country': 'Elegir país o torneo',
      'choose_team': 'Elegir equipo',
      'continue': 'CONTINUAR',
      'alarm_set': 'CONFIGURANDO ALARMA',
      'set_alarms': 'ALARMES CONFIGURADAS',
      'no_alarm': "Añadir nueva alarma",
      'alarm_3_days': '3 DÍAS ANTES',
      'alarm_24_hours': '24 HORAS ANTES',
      'alarm_match_start': 'INICIO DEL PARTIDO',
      'alarm_match_result': 'RESULTADO DEL PARTIDO',
      'home': 'INICIO',
      'exit': 'SALIR',
      'test': 'TEST',
      'settings_user': 'USUARIO',
      'settings_plan': 'PLAN',
      'settings_support': 'SOPORTE',
      'settings_language': 'IDIOMA',
      'settings_sound': 'SONIDO DE NOTIFICACIÓN',
      'settings_logoff': 'CERRAR SESIÓN',
      'plan_standard': 'ESTÁNDAR',
      'upgrade_title': '¿POR QUE MEJORAR?',
      'upgrade_desc1': 'NO TE PIERDAS NINGÚN PARTIDO',
      'upgrade_desc2': 'ALARMES PARA 30 EQUIPOS',
      'upgrade_price': 'Presione el botón de actualización para la suscripción mensual',
      'upgrade_subscription_msg': 'Presione el botón de actualización para la suscripción mensual',
      'upgrade_button': 'MEJORAR',
      'loading': 'Cargando...',
      'on': 'ACTIVO',
      'off': 'INACTIVO',
      'no_selected_alarm': 'Sin alarma seleccionada',
      'add_alarm': 'AÑA. ALARMA',
      'delete_alarm': 'BOR. ALARMA',
      'about_us': 'Sobre nosotros',
      'menu_settings': 'AJUSTES',
      'menu_logoff': 'SALIR',
      'menu_exit': 'SALIR',
      'menu_history': 'HISTORIAL',
      'history_title': 'HISTORIAL DE ALARMAS',
      'premium_warning': 'Hazte Premium para más alarmas',
      'premium_confirm_title': 'Pasando a modo Premium.',
      'premium_confirm_body': '¿Estás seguro?',
      'yes': 'SÍ',
      'no': 'NO',
      'premium_exit_title': 'Saliendo de modo Premium.',
      'premium_exit_body': '¿Cambiar a usuario estándar?',
      'special_user': 'USUARIO ESPECIAL',
      'premium_status': 'Eres usuario Premium.',
      'premium_limit_info': 'Usuarios especiales: 30 alarmas.',
      'privacy_policy': 'Privacidad',
      'api_error_403': '403 Prohibido: No incluido en tu plan.',
      'api_error_404': '404 No encontrado: Error ID equipo.',
      'api_empty_list': 'Lista vacía: Sin partidos programados.',
      'notif_3days': 'Faltan 3 días para el partido.',
      'notif_24hours': 'Faltan 24 horas para el partido.',
      'notif_starts': '¡El partido está empezando!',
      'match_result_prefix': 'Resultado del Partido',
      'match_result_not_ready': 'El resultado aún no está listo, por favor espera.',
      'match_finished_msg': 'Partido terminado',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) terminó. Último partido de {teamName} contra {homeTeam} - {awayTeam}.',
      'no_finished_match': 'No se encontró registro de partido terminado para {teamName}.',
      'api_error': 'Error de datos',
      'connection_error': 'Error de conexión. Revisa tu internet.',
      'test_no_alarm_info': 'No has configurado ninguna alarma. Añade una para probar.',
      'test_notif_incoming': 'La notificación de prueba llegará en 2 segundos.',
      'team_id_error': 'No se pudieron obtener datos del equipo.',
      'ad_loading': 'CARGANDO ANUNCIO...',
      'max_alarm_limit': 'Máximo 30 alarmas permitidas.',
      'no_history_found': 'HISTORIAL VACÍO',
      'premium_active_msg': '¡Modo Premium Activado!',
      'standard_active_msg': '¡Modo Estándar Activado!',
      'will_start': 'comenzará.',
      'history_clear': 'LIMPIAR',
      'history_deleted': 'Registros de historial seleccionados eliminados.',
      'btn_exit_clear': 'LIMPIAR',
    },
    'it': {
      'language_name': 'Italiano',
      'lang_tr': 'Turco',
      'lang_en': 'Inglese',
      'lang_pt': 'Portoghese',
      'lang_de': 'Tedesco',
      'lang_fr': 'Francese',
      'lang_it': 'Italiano',
      'lang_es': 'Spagnolo',
      'lang_nl': 'Olandese',
      'lang_zh': 'Cinese Mandarino',
      'lang_hi': 'Hindi',
      'lang_ar': 'Arabo',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Indonesiano',
      'lang_bn': 'Bengalese',
      'main_title': 'ALLARME CALCIO',
      'nav_main': 'HOME',
      'nav_alarms': 'ALLARMI',
      'nav_settings': 'IMPOSTAZIONI',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'ACCEDI',
      'no_account': 'Senza account?',
      'has_account': 'Hai già un account?',
      'register': 'Registrati',
      'login': 'Accedi',
      'choose_country': 'Scegli paese o torneo',
      'choose_team': 'Scegli squadra',
      'continue': 'CONTINUA',
      'alarm_set': 'IMPOSTAZIONE ALLARME',
      'set_alarms': 'ALLARMI IMPOSTATI',
      'no_alarm': "Aggiungi nuovo allarme",
      'alarm_3_days': '3 GIORNI PRIMA',
      'alarm_24_hours': '24 ORE PRIMA',
      'alarm_match_start': 'INIZIO PARTITA',
      'alarm_match_result': 'RISULTATO PARTITA',
      'home': 'HOME',
      'exit': 'ESCI',
      'test': 'TEST',
      'settings_user': 'UTENTE',
      'settings_plan': 'PIANO',
      'settings_support': 'SUPPORTO',
      'settings_language': 'LINGUA',
      'settings_sound': 'SUONO NOTIFICA',
      'settings_logoff': 'DISCONNETTI',
      'plan_standard': 'STANDARD',
      'upgrade_title': 'PERCHÉ FARE L\'UPGRADE?',
      'upgrade_desc1': 'NON PERDERE NESSUNA PARTITA',
      'upgrade_desc2': 'ALLARMI PER 30 SQUADRE',
      'upgrade_price': 'Premere il pulsante di aggiornamento per l\'abbonamento mensile',
      'upgrade_subscription_msg': 'Premere il pulsante di aggiornamento per l\'abbonamento mensile',
      'upgrade_button': 'UPGRADE',
      'loading': 'Caricamento...',
      'on': 'ON',
      'off': 'OFF',
      'no_selected_alarm': 'Nessun allarme selezionato',
      'add_alarm': 'AGG. ALLARME',
      'delete_alarm': 'ELI. ALLARME',
      'about_us': 'Chi siamo',
      'menu_settings': 'IMPOSTAZIONI',
      'menu_logoff': 'DISCONNETTI',
      'menu_exit': 'ESCI',
      'menu_history': 'CRONOLOGIA',
      'history_title': 'STORICO ALLARMI',
      'premium_warning': 'Passa a Premium per più allarmi',
      'premium_confirm_title': 'Passaggio a modalità Premium.',
      'premium_confirm_body': 'Sei sicuro?',
      'yes': 'SÌ',
      'no': 'NO',
      'premium_exit_title': 'Uscita da modalità Premium.',
      'premium_exit_body': 'Passare a utente standard?',
      'special_user': 'UTENTE SPECIALE',
      'premium_status': 'Sei un utente Premium.',
      'premium_limit_info': 'Gli utenti speciali hanno 30 allarmi.',
      'privacy_policy': 'Privacy',
      'api_error_403': '403 Prohibito: Non incluso nel tuo piano.',
      'api_error_404': '404 Non trovato: Errore ID squadra.',
      'api_empty_list': 'Lista vuota: Nessuna partita trovata.',
      'notif_3days': 'Mancano 3 giorni alla partita.',
      'notif_24hours': 'Mancano 24 ore alla partita.',
      'notif_starts': 'La partita sta iniziando!',
      'match_result_prefix': 'Risultato Partita',
      'match_result_not_ready': 'Il risultato non è ancora pronto, attendere prego.',
      'match_finished_msg': 'Partita finita',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) finita. Ultima partita di {teamName} contra {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Nessuna partita terminata per {teamName} trovata.',
      'api_error': 'Errore dati',
      'connection_error': 'Errore di connessione. Controlla internet.',
      'test_no_alarm_info': 'Nessun allarme impostato. Aggiungine uno per provare.',
      'test_notif_incoming': 'La notifica di test arriverà tra 2 secondi.',
      'team_id_error': 'Dati non trovati per la squadra selezionata.',
      'ad_loading': 'CARICAMENTO PUBBLICITÀ...',
      'max_alarm_limit': 'Massimo 30 allarmi consentiti.',
      'no_history_found': 'NESSUNA CRONOLOGIA TUTTA',
      'premium_active_msg': 'Modalità Premium Attiva!',
      'standard_active_msg': 'Modalità Standard Attiva!',
      'will_start': 'inizierà.',
      'history_clear': 'PULISCI',
      'history_deleted': 'Record storici selezionati eliminati.',
      'btn_exit_clear': 'PULISCI',
    },
    'nl': {
      'language_name': 'Nederlands',
      'lang_tr': 'Turks',
      'lang_en': 'Engels',
      'lang_pt': 'Portugees',
      'lang_de': 'Duits',
      'lang_fr': 'Frans',
      'lang_it': 'Italiaans',
      'lang_es': 'Spaans',
      'lang_nl': 'Nederlands',
      'lang_zh': 'Mandarijn Chinees',
      'lang_hi': 'Hindi',
      'lang_ar': 'Arabisch',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Indonesisch',
      'lang_bn': 'Bengaals',
      'main_title': 'VOETBAL ALARM',
      'nav_main': 'START',
      'nav_alarms': 'ALARMEN',
      'nav_settings': 'INSTELLINGEN',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'INLOGGEN',
      'no_account': 'Geen account?',
      'has_account': 'Al een account?',
      'register': 'Registreren',
      'login': 'Inloggen',
      'choose_country': 'Kies land of toernooi',
      'choose_team': 'Kies team',
      'continue': 'DOORGAAN',
      'alarm_set': 'ALARM INSTELLEN',
      'set_alarms': 'INGESTELDE ALARMEN',
      'no_alarm': "Nieuw alarm toevoegen",
      'alarm_3_days': '3 DAGEN VAN TEVOREN',
      'alarm_24_hours': '24 UUR VAN TEVOREN',
      'alarm_match_start': 'START WEDSTRIJD',
      'alarm_match_result': 'WEDSTRIJDRESULTAAT',
      'home': 'HOME',
      'exit': 'AFSLUITEN',
      'test': 'TEST',
      'settings_user': 'GEBRUIKER',
      'settings_plan': 'PAKKET',
      'settings_support': 'SUPPORT',
      'settings_language': 'TAAL',
      'settings_sound': 'MELDINGSGELUID',
      'settings_logoff': 'UITLOGGEN',
      'plan_standard': 'STANDAARD',
      'upgrade_title': 'WAAROM UPGRADEN?',
      'upgrade_desc1': 'MIS GEEN ENKELE WEDSTRIJD',
      'upgrade_desc2': 'ALARMEN VOOR 30 TEAMS',
      'upgrade_price': 'Druk op de upgrade-knop voor een maandelijks abonnement',
      'upgrade_subscription_msg': 'Druk op de upgrade-knop voor een maandelijks abonnement',
      'upgrade_button': 'UPGRADE',
      'loading': 'Laden...',
      'on': 'AAN',
      'off': 'UIT',
      'no_selected_alarm': 'Geen alarm geselecteerd',
      'add_alarm': 'ALARM TOEV.',
      'delete_alarm': 'ALARM VERWI.',
      'about_us': 'Over ons',
      'menu_settings': 'INSTELLINGEN',
      'menu_logoff': 'UITLOGGEN',
      'menu_exit': 'STOP',
      'menu_history': 'GESCHIEDENIS',
      'history_title': 'ALARM HISTORIE',
      'premium_warning': 'Word Premium voor mehr alarmen',
      'premium_confirm_title': 'Naar Premium-modus.',
      'premium_confirm_body': 'Weet u het zeker?',
      'yes': 'JA',
      'no': 'NEE',
      'premium_exit_title': 'Premium-modus verlaten.',
      'premium_exit_body': 'Naar standaardgebruiker?',
      'special_user': 'SPECIALE GEBRUIKER',
      'premium_status': 'U bent bir Premium-gebruuber.',
      'premium_limit_info': 'Speciale gebruikers hebben 30 alarmen.',
      'privacy_policy': 'Privacybeleid',
      'api_error_403': '403 Verboden: Niet in uw pakket.',
      'api_error_404': '404 Niet gevonden: Team ID fout.',
      'api_empty_list': 'Leere Liste: Keine Spiele gefunden.',
      'notif_3days': 'Nog 3 dagen tot de wedstrijd.',
      'notif_24hours': 'Nog 24 uur tot de wedstrijd.',
      'notif_starts': 'De wedstrijd begint!',
      'match_result_prefix': 'Wedstrijdresultaat',
      'match_result_not_ready': 'Het resultaat is nog niet klaar, even geduld a.u.b.',
      'match_finished_msg': 'Wedstrijd afgelopen',
      'test_match_finished_msg': 'TEST {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) afgelopen. Laatste wedstrijd van {teamName} tegen {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Geen afgelopen wedstrijd gevonden voor {teamName}.',
      'api_error': 'Gegevensfout',
      'connection_error': 'Verbindingsfout. Controleer internet.',
      'test_no_alarm_info': 'Nog geen alarm ingesteld. Voeg er bir toe om te testen.',
      'test_notif_incoming': 'Testmelding komt over 2 seconden.',
      'team_id_error': 'Kon gegevens voor team niet ophalen.',
      'ad_loading': 'ADVERTENTIE LADEN...',
      'max_alarm_limit': 'Maximaal 30 alarmen toegestaan.',
      'no_history_found': 'GEEN GESCHIEDENIS GEVONDEN',
      'premium_active_msg': 'Premium-modus Aan!',
      'standard_active_msg': 'Standaard-modus Aan!',
      'will_start': 'zal beginnen.',
      'history_clear': 'WISSEN',
      'history_deleted': 'Geselecteerde geschiedenisrecords verwijderd.',
      'btn_exit_clear': 'WISSEN',
    },
    'hi': {
      'language_name': 'हिन्दी',
      'lang_tr': 'तुर्की',
      'lang_en': 'अंग्रेज़ी',
      'lang_pt': 'पुर्तगाली',
      'lang_de': 'जर्मन',
      'lang_fr': 'फ्रेंच',
      'lang_it': 'इतालवी',
      'lang_es': 'स्पेनिश',
      'lang_nl': 'डच',
      'lang_zh': 'मंदारिन चीनी',
      'lang_hi': 'हिन्दी',
      'lang_ar': 'अरबी',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'इंडोनेशियाई',
      'lang_bn': 'बंगाली',
      'main_title': 'फुटबॉल अलार्म',
      'nav_main': 'मुख्य पृष्ठ',
      'nav_alarms': 'अलार्म',
      'nav_settings': 'सेटिंग्स',
      'nav_upgrade': 'अपग्रेड',
      'login_title': 'लॉग इन करें',
      'no_account': 'अकाउंट नहीं है?',
      'has_account': 'अकाउंट है?',
      'register': 'पंजीकरण',
      'login': 'लॉग इन',
      'choose_country': 'देश या टूर्नामेंट चुनें',
      'choose_team': 'टीम चुनें',
      'continue': 'जारी रखें',
      'alarm_set': 'अलार्म सेट हो रहा है',
      'set_alarms': 'सेट अलार्म',
      'no_alarm': "नया अलार्म जोड़ें",
      'alarm_3_days': '3 दिन पहले',
      'alarm_24_hours': '24 घंटे पहले',
      'alarm_match_start': 'मैच शुरू',
      'alarm_match_result': 'मैच का परिणाम',
      'home': 'होम',
      'exit': 'निकास',
      'test': 'टेस्ट',
      'settings_user': 'उपयोगकर्ता',
      'settings_plan': 'प्लान',
      'settings_support': 'सहायता केंद्र',
      'settings_language': 'भाषा',
      'settings_sound': 'नोटिफिकेशन ध्वनि',
      'settings_logoff': 'लॉग आउट',
      'plan_standard': 'स्टैंडर्ड',
      'upgrade_title': 'अपग्रेड क्यों करें?',
      'upgrade_desc1': 'कोई मैच नहीं छूटेगा',
      'upgrade_desc2': '30 टीमों के लिए अलार्म सेट करें',
      'upgrade_price': 'मासिक सदस्यता के लिए अपग्रेड बटन दबाएं',
      'upgrade_subscription_msg': 'मासिक सदस्यता के लिए अपग्रेड बटन दबाएं',
      'upgrade_button': 'अपग्रेड',
      'loading': 'मैच लोड हो रहा है...',
      'on': 'चालू',
      'off': 'बंद',
      'no_selected_alarm': 'कोई अलार्म नहीं चुना गया',
      'add_alarm': 'अलार्म जोड़ें',
      'delete_alarm': 'अलार्म हटाएं',
      'about_us': 'हमारे बारे में',
      'menu_settings': 'सेटिंग्स',
      'menu_logoff': 'लॉग आउट',
      'menu_exit': 'निकास',
      'menu_history': 'अलार्म इतिहास',
      'history_title': 'अलार्म इतिहास',
      'premium_warning': 'अधिक अलार्म के लिए प्रीमियम सदस्य बनें',
      'premium_confirm_title': 'प्रीमियम मोड में जा रहे हैं।',
      'premium_confirm_body': 'क्या आप सुनिश्चित हैं?',
      'yes': 'हाँ',
      'no': 'नहीं',
      'premium_exit_title': 'प्रीमियम मोड छोड़ रहे हैं।',
      'premium_exit_body': 'स्टैंडर्ड यूजर पर स्विच करें?',
      'special_user': 'विशेष उपयोगकर्ता',
      'premium_status': 'आप एक प्रीमियम यूजर हैं।',
      'premium_limit_info': 'विशेष उपयोगकर्ता 30 अलार्म सेट कर सकते हैं।',
      'privacy_policy': 'गोपनीयता नीति',
      'api_error_403': '403 वर्जित: आपके प्लान में नहीं।',
      'api_error_404': '404 नहीं मिला: टीम आईडी त्रुटि।',
      'api_empty_list': 'खाली सूची: कोई मैच नहीं मिला।',
      'notif_3days': 'मैच के लिए 3 दिन बाकी हैं।',
      'notif_24hours': 'मैच के लिए 24 घंटे बाकी हैं।',
      'notif_starts': 'मैच शुरू हो रहा है!',
      'match_result_prefix': 'मैच परिणाम',
      'match_result_not_ready': 'परिणाम अभी तैयार नहीं है, कृपया प्रतीक्षा करें।',
      'match_finished_msg': 'खेल खत्म',
      'test_match_finished_msg': 'टेस्ट {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) मैच समाप्त। {teamName} का अंतिम मैच {homeTeam} - {awayTeam} के बीच था।',
      'no_finished_match': '{teamName} के लिए कोई समाप्त मैच नहीं मिला।',
      'api_error': 'डेटा त्रुटि',
      'connection_error': 'कनेक्शन त्रुटि। इंटरनेट जांचें।',
      'test_no_alarm_info': 'अभी तक कोई अलार्म सेट नहीं किया गया। परीक्षण के लिए जोड़ें।',
      'test_notif_incoming': 'परीक्षण सूचना 2 सेकंड में आएगी।',
      'team_id_error': 'चुनी गई टीम के लिए डैटा नहीं मिला।',
      'ad_loading': 'विज्ञापन लोड हो रहा है...',
      'max_alarm_limit': 'अधिकतम 30 अलार्म संभव हैं।',
      'no_history_found': 'कोई इतिहास नहीं मिला',
      'premium_active_msg': 'प्रीमियम मोड चालू!',
      'standard_active_msg': 'स्टैंडर्ड मोड चालू!',
      'will_start': 'शुरू होगा।',
      'history_clear': 'साफ करें',
      'history_deleted': 'चुने गए इतिहास रिकॉर्ड हटा दिए गए।',
      'btn_exit_clear': 'साफ करें',
    },
    'ar': {
      'language_name': 'العربية',
      'lang_tr': 'التركية',
      'lang_en': 'الإنجليزية',
      'lang_pt': 'البرتغالية',
      'lang_de': 'الألمانية',
      'lang_fr': 'الفرنسية',
      'lang_it': 'الإيطالية',
      'lang_es': 'الإسبانية',
      'lang_nl': 'الهولندية',
      'lang_zh': 'الصينية الماندرين',
      'lang_hi': 'الهندية',
      'lang_ar': 'العربية',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'الإندونيسية',
      'lang_bn': 'البنغالية',
      'main_title': 'منبه كرة القدم',
      'nav_main': 'الرئيسية',
      'nav_alarms': 'التنبيهات',
      'nav_settings': 'الإعدادات',
      'nav_upgrade': 'ترقية',
      'login_title': 'تسجيل الدخول',
      'no_account': 'ليس لديك حساب؟',
      'has_account': 'لديك حساب بالفعل؟',
      'register': 'سجل الآن',
      'login': 'دخول',
      'choose_country': 'اختر الدولة أو البطولة',
      'choose_team': 'اختر الفريق',
      'continue': 'استمرار',
      'alarm_set': 'جاري ضبط التنبيه',
      'set_alarms': 'التنبيهات المضبوطة',
      'no_alarm': "إضافة تنبيه جديد",
      'alarm_3_days': 'قبل 3 أيام',
      'alarm_24_hours': 'قبل 24 ساعة',
      'alarm_match_start': 'بداية المباراة',
      'alarm_match_result': 'نتيجة المباراة',
      'home': 'الرئيسية',
      'exit': 'خروج',
      'test': 'تجربة',
      'settings_user': 'المستخدم',
      'settings_plan': 'الباقة',
      'settings_support': 'مركز الدعم',
      'settings_language': 'اللغة',
      'settings_sound': 'صوت الإشعارات',
      'settings_logoff': 'تسجيل الخروج',
      'plan_standard': 'قياسي',
      'upgrade_title': 'لماذا الترقية؟',
      'upgrade_desc1': 'لن تفوتك أي مباراة',
      'upgrade_desc2': 'ضبط تنبيهات لـ 30 فريقاً',
      'upgrade_price': 'اضغط على زر الترقية للاشتراك الشهري',
      'upgrade_subscription_msg': 'اضغط على زر الترقية للاشتراك الشهري',
      'upgrade_button': 'ترقية',
      'loading': 'جاري التحميل...',
      'on': 'تشغيل',
      'off': 'إيقاف',
      'no_selected_alarm': 'لا يوجد تنبيه مختار',
      'add_alarm': 'إضافة تنبيه',
      'delete_alarm': 'حذف التنبيه',
      'about_us': 'من نحن',
      'menu_settings': 'الإعدادات',
      'menu_logoff': 'خروج',
      'menu_exit': 'خروج',
      'menu_history': 'سجل التنبيهات',
      'history_title': 'تاريخ التنبيهات',
      'premium_warning': 'اشترك في بريميوم لمزيد من التنبيهات',
      'premium_confirm_title': 'الانتقال إلى وضع بريميوم.',
      'premium_confirm_body': 'هل أنت متأكد؟',
      'yes': 'نعم',
      'no': 'لا',
      'premium_exit_title': 'الخروج من وضع بريميوم.',
      'premium_exit_body': 'التحويل إلى مستخدم قياسي؟',
      'special_user': 'مستخدم خاص',
      'premium_status': 'أنت مستخدم بريميوم.',
      'premium_limit_info': 'المستخدم الخاص يمكنه ضبط 30 تنبيهاً.',
      'privacy_policy': 'سياسة الخصوصية',
      'api_error_403': '403 ممنوع: غير مدرج في باقتك.',
      'api_error_404': '404 غير موجود: خطأ في معرف الفريق.',
      'api_empty_list': 'قائمة فارغة: لم يتم العثور على مباريات.',
      'notif_3days': 'بقي 3 أيام على المباراة.',
      'notif_24hours': 'بقي 24 ساعة على المباراة.',
      'notif_starts': 'المباراة تبدأ الآن!',
      'match_result_prefix': 'نتيجة المباراة',
      'match_result_not_ready': 'النتيجة ليست جاهزة بعد، يرجى الانتظار.',
      'match_finished_msg': 'انتهت المباراة',
      'test_match_finished_msg': 'تجربة {homeTeam} ({homeScore})، {awayTeam} ({awayScore}) انتهت المباراة. آخر مباراة لفريقك {teamName} كانت ضد {homeTeam} - {awayTeam}.',
      'no_finished_match': 'لم يتم العثور على سجل مباراة منتهية للفريق {teamName}.',
      'api_error': 'خطأ في البيانات',
      'connection_error': 'خطأ في الاتصال. يرجى التحقق من الإنترنت.',
      'test_no_alarm_info': 'لم تقم بضبط أي تنبيه بعد. يرجى إضافة تنبيه للتجربة.',
      'test_notif_incoming': 'سيصل إشعار التجربة خلال ثانيتين.',
      'team_id_error': 'تعذر جلب البيانات للفريق المختار.',
      'ad_loading': 'جاري تحميل الإعلان...',
      'max_alarm_limit': 'يمكنك ضبط 30 تنبيهاً كحد أقصى.',
      'no_history_found': 'لا يوجد سجل تنبيهات',
      'premium_active_msg': 'وضع بريميوم مفعل!',
      'standard_active_msg': 'الوضع القياسي مفعل!',
      'will_start': 'سوف تبدأ.',
      'history_clear': 'مسح',
      'history_deleted': 'تم حذف سجلات المحفوظات المحددة.',
      'btn_exit_clear': 'مسح',
    },
    'ru': {
      'language_name': 'Русский',
      'lang_tr': 'Турецкий',
      'lang_en': 'Английский',
      'lang_pt': 'Португальский',
      'lang_de': 'Немецкий',
      'lang_fr': 'Французский',
      'lang_it': 'Итальянский',
      'lang_es': 'Испанский',
      'lang_nl': 'Голландский',
      'lang_zh': 'Китайский',
      'lang_hi': 'Хинди',
      'lang_ar': 'Арабский',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Индонезийский',
      'lang_bn': 'Бенгальский',
      'main_title': 'ФУТБОЛЬНЫЙ БУДИЛЬНИК',
      'nav_main': 'ГЛАВНАЯ',
      'nav_alarms': 'БУДИЛЬНИКИ',
      'nav_settings': 'НАСТРОЙКИ',
      'nav_upgrade': 'УЛУЧШИТЬ',
      'login_title': 'ВХОД',
      'no_account': 'Нет аккаунта?',
      'has_account': 'Уже есть аккаунт?',
      'register': 'Регистрация',
      'login': 'Войти',
      'choose_country': 'Выберите страну или турнир',
      'choose_team': 'Выберите команду',
      'continue': 'ПРОДОЛЖИТЬ',
      'alarm_set': 'УСТАНОВКА БУДИЛЬНИКА',
      'set_alarms': 'УСТАНОВЛЕННЫЕ БУДИЛЬНИКИ',
      'no_alarm': "Добавить новый будильник",
      'alarm_3_days': 'ЗА 3 ДНЯ',
      'alarm_24_hours': 'ЗА 24 ЧАСА',
      'alarm_match_start': 'НАЧАЛО МАТЧА',
      'alarm_match_result': 'РЕЗУЛЬТАТ МАТЧА',
      'home': 'ДОМОЙ',
      'exit': 'ВЫХОД',
      'test': 'ТЕСТ',
      'settings_user': 'ПОЛЬЗОВАТЕЛЬ',
      'settings_plan': 'ПАКЕТ',
      'settings_support': 'ПОДДЕРЖКА',
      'settings_language': 'ЯЗЫК',
      'settings_sound': 'ЗВУК УВЕДОМЛЕНИЯ',
      'settings_logoff': 'ВЫЙТИ',
      'plan_standard': 'СТАНДАРТ',
      'upgrade_title': 'ЗАЧЕМ УЛУЧШАТЬ?',
      'upgrade_desc1': 'ВЫ НЕ ПРОПУСТИТЕ НИ ОДНОГО МАТЧА',
      'upgrade_desc2': 'БУДИЛЬНИКИ ДЛЯ 30 КОМАНД',
      'upgrade_price': 'Нажмите кнопку обновления для ежемесячной подписки',
      'upgrade_subscription_msg': 'Нажмите кнопку обновления для ежемесячной подписки',
      'upgrade_button': 'УЛУЧШИТЬ',
      'loading': 'Загрузка...',
      'on': 'ВКЛ',
      'off': 'ВЫКЛ',
      'no_selected_alarm': 'Будильник не выбран',
      'add_alarm': 'ДОБАВИТЬ',
      'delete_alarm': 'УДАЛИТЬ',
      'about_us': 'О нас',
      'menu_settings': 'НАСТРОЙКИ',
      'menu_logoff': 'ВЫЙТИ',
      'menu_exit': 'ВЫХОД',
      'menu_history': 'ИСТОРИЯ',
      'history_title': 'ИСТОРИЯ БУДИЛЬНИКОВ',
      'premium_warning': 'Станьте Premium для большего числа будильников',
      'premium_confirm_title': 'Переход в Premium режим.',
      'premium_confirm_body': 'Вы уверены?',
      'yes': 'ДА',
      'no': 'НЕТ',
      'premium_exit_title': 'Выход из Premium режима.',
      'premium_exit_body': 'Перейти на стандартного пользователя?',
      'special_user': 'СПЕЦПОЛЬЗОВАТЕЛЬ',
      'premium_status': 'Вы Premium пользователь.',
      'premium_limit_info': 'Спецпользователи могут ставить 30 будильников.',
      'privacy_policy': 'Конфиденциальность',
      'api_error_403': '403 Запрещено: Не включено в ваш план.',
      'api_error_404': '404 Не найдено: Ошибка ID команды.',
      'api_empty_list': 'Пустой список: Матчи не найдены.',
      'notif_3days': 'До матча осталось 3 дня.',
      'notif_24hours': 'До матча осталось 24 часа.',
      'notif_starts': 'Матч начинается!',
      'match_result_prefix': 'Результат матча',
      'match_result_not_ready': 'Результат еще не готов, пожалуйста, подождите.',
      'match_finished_msg': 'Матч окончен',
      'test_match_finished_msg': 'ТЕСТ {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) матч завершен. Последний матч {teamName} был против {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Завершенных матчей для команды {teamName} не найдено.',
      'api_error': 'Ошибка данных',
      'connection_error': 'Ошибка соединения. Проверьте интернет.',
      'test_no_alarm_info': 'Будильник не установлен. Добавьте для теста.',
      'test_notif_incoming': 'Тестовое уведомление придет через 2 секунды.',
      'team_id_error': 'Данные для выбранной команды не найдены.',
      'ad_loading': 'ЗАГРУЗКА РЕКЛАМЫ...',
      'max_alarm_limit': 'Максимум 30 будильников.',
      'no_history_found': 'ИСТОРИЯ ПУСТА',
      'premium_active_msg': 'Premium режим включен!',
      'standard_active_msg': 'Стандартный режим включен!',
      'will_start': 'начнется.',
      'history_clear': 'ОЧИСТИТЬ',
      'history_deleted': 'Выбранные записи истории удалены.',
      'btn_exit_clear': 'ОЧИСТИТЬ',
    },
    'id': {
      'language_name': 'Indonesia',
      'lang_tr': 'Turki',
      'lang_en': 'Inggris',
      'lang_pt': 'Portugis',
      'lang_de': 'Jerman',
      'lang_fr': 'Prancis',
      'lang_it': 'Italia',
      'lang_es': 'Spanyol',
      'lang_nl': 'Belanda',
      'lang_zh': 'Mandarin',
      'lang_hi': 'Hindi',
      'lang_ar': 'Arab',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'Indonesia',
      'lang_bn': 'Bengali',
      'main_title': 'ALARM SEPAK BOLA',
      'nav_main': 'UTAMA',
      'nav_alarms': 'ALARM',
      'nav_settings': 'PENGATURAN',
      'nav_upgrade': 'UPGRADE',
      'login_title': 'MASUK',
      'no_account': 'Belum punya akun?',
      'has_account': 'Sudah punya akun?',
      'register': 'Daftar',
      'login': 'Masuk',
      'choose_country': 'Pilih Negara atau Turnamen',
      'choose_team': 'Pilih Tim',
      'continue': 'LANJUT',
      'alarm_set': 'MENGATUR ALARM',
      'set_alarms': 'ALARM TERPASANG',
      'no_alarm': "Tambah Alarm Baru",
      'alarm_3_days': '3 HARI SEBELUM',
      'alarm_24_hours': '24 JAM SEBELUM',
      'alarm_match_start': 'PERTANDINGAN DIMULAI',
      'alarm_match_result': 'HASIL PERTANDINGAN',
      'home': 'BERANDA',
      'exit': 'KELUAR',
      'test': 'TES',
      'settings_user': 'PENGGUNA',
      'settings_plan': 'PAKET',
      'settings_support': 'PUSAT BANTUAN',
      'settings_language': 'BAHASA',
      'settings_sound': 'SUARA NOTIFIKASI',
      'settings_logoff': 'KELUAR',
      'plan_standard': 'STANDAR',
      'upgrade_title': 'MENGAPA UPGRADE?',
      'upgrade_desc1': 'JANGAN LEWATKAN PERTANDINGAN',
      'upgrade_desc2': 'SET ALARM UNTUK 30 TIM',
      'upgrade_price': 'Tekan tombol upgrade untuk berlangganan bulanan',
      'upgrade_subscription_msg': 'Tekan tombol upgrade untuk berlangganan bulanan',
      'upgrade_button': 'UPGRADE',
      'loading': 'Memuat...',
      'on': 'AKTIF',
      'off': 'NONAKTIF',
      'no_selected_alarm': 'Tidak ada alarm terpilih',
      'add_alarm': 'TAMB. ALARM',
      'delete_alarm': 'HAPUS ALARM',
      'about_us': 'Tentang Kami',
      'menu_settings': 'PENGATURAN',
      'menu_logoff': 'KELUAR',
      'menu_exit': 'KELUAR',
      'menu_history': 'RIWAYAT',
      'history_title': 'RIWAYAT ALARM',
      'premium_warning': 'Jadi pengguna Premium untuk lebih banyak alarm Indonesian',
      'premium_confirm_title': 'Beralih ke mode Premium.',
      'premium_confirm_body': 'Anda yakin?',
      'yes': 'YA',
      'no': 'TIDAK',
      'premium_exit_title': 'Keluar dari mode Premium.',
      'premium_exit_body': 'Beralih ke pengguna standar?',
      'special_user': 'PENGGUNA KHUSUS',
      'premium_status': 'Anda pengguna Premium.',
      'premium_limit_info': 'Pengguna khusus dapat mengatur 30 alarm.',
      'privacy_policy': 'Kebijakan Privasi',
      'api_error_403': '403 Terlarang: Tidak termasuk dalam paket Anda.',
      'api_error_404': '404 Tidak ditemukan: Kesalahan ID tim.',
      'api_empty_list': 'Daftar Kosong: Pertandingan tidak ditemukan.',
      'notif_3days': '3 hari lagi menuju pertandingan.',
      'notif_24hours': '24 jam lagi menuju pertandingan.',
      'notif_starts': 'Pertandingan dimulai!',
      'match_result_prefix': 'Hasil Pertandingan',
      'match_result_not_ready': 'Hasil belum siap, harap tunggu.',
      'match_finished_msg': 'Pertandingan berakhir',
      'test_match_finished_msg': 'TES {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) pertandingan berakhir. Pertandingan terakhir {teamName} adalah melawan {homeTeam} - {awayTeam}.',
      'no_finished_match': 'Tidak ada catatan pertandingan berakhir untuk {teamName}.',
      'api_error': 'Kesalahan data',
      'connection_error': 'Kesalahan koneksi. Periksa internet Anda.',
      'test_no_alarm_info': 'Belum ada alarm. Tambahkan satu untuk tes.',
      'test_notif_incoming': 'Notifikasi tes akan tiba dalam 2 detik.',
      'team_id_error': 'Data tidak ditemukan untuk tim terpilih.',
      'ad_loading': 'MEMUAT IKLAN...',
      'max_alarm_limit': 'Maksimal 30 alarm diperbolehkan.',
      'no_history_found': 'RIWAYAT KOSONG',
      'premium_active_msg': 'Mode Premium Aktif!',
      'standard_active_msg': 'Mode Standar Aktiva!',
      'will_start': 'akan dimulai.',
      'history_clear': 'BERSIHKAN',
      'history_deleted': 'Catatan riwayat yang dipilih dihapus.',
      'btn_exit_clear': 'BERSIHKAN',
    },
    'ja': {
      'language_name': '日本語',
      'lang_tr': 'トルコ語',
      'lang_en': '英語',
      'lang_pt': 'ポルトガル語',
      'lang_de': 'ドイツ語',
      'lang_fr': 'フランス語',
      'lang_it': 'イタリア語',
      'lang_es': 'スペイン語',
      'lang_nl': 'オランダ語',
      'lang_zh': '中国語',
      'lang_hi': 'ヒンディー語',
      'lang_ar': 'アラビア語',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': 'インドネシア語',
      'lang_bn': 'ベンガル語',
      'main_title': 'サッカーアラーム',
      'nav_main': 'メイン',
      'nav_alarms': 'アラーム',
      'nav_settings': '設定',
      'nav_upgrade': 'アップグレード',
      'login_title': 'ログイン',
      'no_account': 'アカウントをお持ちでないですか？',
      'has_account': 'アカウントをお持ちですか？',
      'register': '登録',
      'login': 'ログイン',
      'choose_country': '国または大会を選択',
      'choose_team': 'チームを選択',
      'continue': '次へ',
      'alarm_set': 'アラーム設定中',
      'set_alarms': '設定済みアラーム',
      'no_alarm': "新しいアラームを追加",
      'alarm_3_days': '3日前',
      'alarm_24_hours': '24時間前',
      'alarm_match_start': '試合開始',
      'alarm_match_result': '試合結果',
      'home': 'ホーム',
      'exit': '終了',
      'test': 'テスト',
      'settings_user': 'ユーザー',
      'settings_plan': 'プラン',
      'settings_support': 'サポート',
      'settings_language': '言語',
      'settings_sound': '通知音',
      'settings_logoff': 'ログアウト',
      'plan_standard': '標準',
      'upgrade_title': 'アップグレードの理由',
      'upgrade_desc1': '試合を見逃しません',
      'upgrade_desc2': '30チームのアラームを設定可能',
      'upgrade_price': '月額サブスクリプションについてはアップグレードボタンを押してください',
      'upgrade_subscription_msg': '月額サブスクリプションについてはアップグレードボタンを押してください',
      'upgrade_button': 'アップグレード',
      'loading': '読み込み中...',
      'on': 'オン',
      'off': 'オフ',
      'no_selected_alarm': 'アラーム未選択',
      'add_alarm': 'アラーム追加',
      'delete_alarm': 'アラーム削除',
      'about_us': '会社概要',
      'menu_settings': '設定',
      'menu_logoff': 'ログアウト',
      'menu_exit': '終了',
      'menu_history': '履歴',
      'history_title': 'アラーム履歴',
      'premium_warning': 'プレミアム会員になるとより多くのアラームを設定できます',
      'premium_confirm_title': 'プレミアムモードへ切り替え。',
      'premium_confirm_body': 'よろしいですか？',
      'yes': 'はい',
      'no': 'いいえ',
      'premium_exit_title': 'プレミアムモードを終了。',
      'premium_exit_body': '標準ユーザーに切り替えますか？',
      'special_user': '特別ユーザー',
      'premium_status': 'あなたはプレミアムユーザーです。',
      'premium_limit_info': '特別ユーザーは30個のアラームを設定できます。',
      'privacy_policy': 'プライバシーポリシー',
      'api_error_403': '403 Forbidden: プランに含まれていません。',
      'api_error_404': '404 Not Found: チームIDエラー。',
      'api_empty_list': '空リスト: 試合が見つかりません。',
      'notif_3days': '試合まであと3日です。',
      'notif_24hours': '試合まであと24時間です。',
      'notif_starts': '試合が始まります！',
      'match_result_prefix': '試合結果',
      'match_result_not_ready': '結果はまだ準備ができていません。お待ちください。',
      'match_finished_msg': '試合終了',
      'test_match_finished_msg': 'テスト {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) 試合終了。{teamName} の最後の試合は {homeTeam} - {awayTeam} でした。',
      'no_finished_match': '{teamName} の終了した試合は見つかりませんでした。',
      'api_error': 'データ取得エラー',
      'connection_error': '接続エラー。インターネットを確認してください。',
      'test_no_alarm_info': 'アラームが設定されていません。テスト用に追加してください。',
      'test_notif_incoming': 'テスト通知が 2 秒後に届きます。',
      'team_id_error': '選択したチーム의 データが見つかりませんでした。',
      'ad_loading': '広告を読み込み中...',
      'max_alarm_limit': '最大 30 個のアラームを設定可能です。',
      'no_history_found': '履歴が見つかりません',
      'premium_active_msg': 'プレミアムモード有効！',
      'standard_active_msg': '標準モード有効！',
      'will_start': '始まります。',
      'history_clear': 'クリア',
      'history_deleted': '選択した履歴レコードが削除されました。',
      'btn_exit_clear': 'クリア',
    },
    'ko': {
      'language_name': '한국어',
      'lang_tr': '터키어',
      'lang_en': '영어',
      'lang_pt': '포르투갈어',
      'lang_de': '독일어',
      'lang_fr': '프랑스어',
      'lang_it': '이탈리아어',
      'lang_es': '스페인어',
      'lang_nl': '네덜란드어',
      'lang_zh': '중국어',
      'lang_hi': '힌디어',
      'lang_ar': '아랍어',
      'lang_ru': 'Русский',
      'lang_ja': '日本語',
      'lang_ko': '한국어',
      'lang_id': '인도네시아어',
      'lang_bn': '벵골어',
      'main_title': '축구 알람',
      'nav_main': '메인',
      'nav_alarms': '알람',
      'nav_settings': '설정',
      'nav_upgrade': '업그레이드',
      'login_title': '로그인',
      'no_account': '계정이 없으신가요?',
      'has_account': '계정이 있으신가요?',
      'register': '회원가입',
      'login': '로그인',
      'choose_country': '국가 또는 대회 선택',
      'choose_team': '팀 선택',
      'continue': '계속하기',
      'alarm_set': '알람 설정 중',
      'set_alarms': '설정된 알람',
      'no_alarm': "새 알람 추가",
      'alarm_3_days': '3일 전',
      'alarm_24_hours': '24시간 전',
      'alarm_match_start': '경기 시작',
      'alarm_match_result': '경기 결과',
      'home': '홈',
      'exit': '종료',
      'test': '테스트',
      'settings_user': '사용자',
      'settings_plan': '요금제',
      'settings_support': '지원 센터',
      'settings_language': '언어',
      'settings_sound': '알림음',
      'settings_logoff': '로그아웃',
      'plan_standard': '표준',
      'upgrade_title': '업그레이드 이유',
      'upgrade_desc1': '경기를 놓치지 마세요',
      'upgrade_desc2': '30개 팀 알람 설정 가능',
      'upgrade_price': '월간 구독을 위해 업그레이드 버튼을 누르십시오',
      'upgrade_subscription_msg': '월간 구독을 위해 업그레이드 버튼을 누르십시오',
      'upgrade_button': '업그레이드',
      'loading': '로딩 중...',
      'on': '켜짐',
      'off': '꺼짐',
      'no_selected_alarm': '선택된 알람 없음',
      'add_alarm': '알람 추가',
      'delete_alarm': '알람 삭제',
      'about_us': '회사 소개',
      'menu_settings': '설정',
      'menu_logoff': '로그아웃',
      'menu_exit': '종료',
      'menu_history': '기록',
      'history_title': '알람 기록',
      'premium_warning': '더 많은 알람을 위해 프리미엄 사용자가 되세요',
      'premium_confirm_title': '프리미엄 모드로 전환합니다.',
      'premium_confirm_body': '확실합니까?',
      'yes': '예',
      'no': '아니오',
      'premium_exit_title': '프리미엄 모드 종료.',
      'premium_exit_body': '표준 사용자로 전환할까요?',
      'special_user': '특별 사용자',
      'premium_status': '당신은 프리미엄 사용자입니다.',
      'premium_limit_info': '특별 사용자는 30개의 알람을 설정할 수 있습니다.',
      'privacy_policy': '개인정보 보호정책',
      'api_error_403': '403 금지됨: 요금제에 포함되지 않음.',
      'api_error_404': '404 찾을 수 없음: 팀 ID 오류.',
      'api_empty_list': '빈 목록: 예약된 경기가 없습니다.',
      'notif_3days': '경기까지 3일 남았습니다.',
      'notif_24hours': '경기까지 24시간 남았습니다.',
      'notif_starts': '경기가 시작됩니다!',
      'match_result_prefix': '경기 결과',
      'match_result_not_ready': '결과가 아직 준비되지 않았습니다. 잠시 기다려 주십시오.',
      'match_finished_msg': '경기 종료',
      'test_match_finished_msg': '테스트 {homeTeam} ({homeScore}), {awayTeam} ({awayScore}) 경기가 종료되었습니다. 선택한 {teamName} 팀의 마지막 경기는 {homeTeam} - {awayTeam} 였습니다.',
      'no_finished_match': '{teamName} 팀에 대한 종료된 경기 기록을 찾을 수 없습니다.',
      'api_error': '데이터 오류',
      'connection_error': '연결 오류. 인터넷을 확인하세요.',
      'test_no_alarm_info': '알람이 설정되지 않았습니다. 테스트를 위해 추가하세요.',
      'test_notif_incoming': '테스트 알림이 2초 후에 도착합니다.',
      'team_id_error': '선택한 팀의 데이터를 찾을 수 없습니다.',
      'ad_loading': '광고 로딩 중...',
      'max_alarm_limit': '최대 30개의 알람을 설정할 수 있습니다.',
      'no_history_found': '기록을 찾을 수 없음',
      'premium_active_msg': '프리미엄 모드 활성화!',
      'standard_active_msg': '표준 모드 활성화!',
      'will_start': '시작됩니다.',
      'history_clear': '지우기',
      'history_deleted': '선택한 기록이 삭제되었습니다.',
      'btn_exit_clear': '지우기',
    },
  };

  static String getTranslation(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}